---

- hosts: all

  roles:
    - { role: common,                                 tags: common }
    - { role: mivok0.users,                           tags: users }
    - { role: telusdigital.fish,                      tags: fish }
    - { role: geerlingguy.nginx,                      tags: nginx }
    - role: geerlingguy.mysql
      become: yes
      tags: mysql
    - { role: geerlingguy.php,                        tags: php }
    - { role: geerlingguy.php-mysql,                  tags: php-mysql }
    - { role: carlosbuenosvinos.ansistrano-deploy,    tags: ansistrano }
